routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*Route::get('/', function (){
    return view('forum.home');
});*/


Auth::routes();

Route::get('/', 'ForumController@index')->name('forum.home');
/*Route::get('/categories/create', 'ForumController@create')->name('categories.create');
Route::POST('/categories/store', 'ForumController@store')->name('categories.store');
Route::get('home', 'HomeController@index')->name('home');*/
Route::resource('categories', 'ForumCategoryController');
Route::resource('messages', 'ForumThreadController');
Route::get('/threads', 'ForumCategoryController@index')->name('threads.index');

/* Dashboard*/
/*
Route::middleware(['auth'])->group( function(){
    Route::get('home', 'HomeController@index')->name('home');
    Route::resource('categories', 'ForumCategoryController');
    Route::resource('messages', 'ForumThreadController');

});
*/
/*Route::get('/', HomeController@index);*/

/*{
    if(Auth::check() && Auth::user()->role_id == 1) {*/
/*        return redirect('administrator/dashboard');*/
/*        return view('administrator/dashboard');

    }
    elseif(Auth::check() && Auth::user()->role_id == 2){
/*        return redirect('redactor/dashboard');*/
/*        return view('redactor/dashboard');

    }elseif(Auth::check() && Auth::user()->role_id == 3){*/
/*        return redirect('moderator/dashboard');*/
/*        return view('moderator/dashboard');

    }elseif(Auth::check() && Auth::user()->role_id == 4) {*/
/*        return redirect('standard-user/dashboard');*/
//Route::get('/', 'HomeController@index')->name('home');
/*
group(['as'=>'administrator.','prefix' => 'administrator','namespace'=>'Administrator','middleware'=>['auth','administrator']], function () {
    Route::get('administrator', 'AdministratorController@index')->name('administrator');
});

Route::group(['as'=>'redactor.','prefix' => 'redactor','namespace'=>'redactor','middleware'=>['auth','redactor']], function () {
    Route::get('redactor', 'RedactorController@index')->name('redactor');
});


Route::group(['as'=>'moderator.','prefix' => 'moderator','namespace'=>'Moderator','middleware'=>['auth','moderator']], function () {
    Route::get('moderator', 'ModeratorController@index')->name('moderator');
});
Route::group(['as'=>'standard-user.','prefix' => 'standard-user','namespace'=>'StandardUser','middleware'=>['auth','standard-user']], function () {
    Route::get('standard-user', 'StandardUserController@index')->name('standard-user');
});

*/
/*Route::group(['middleware' => 'auth'], function(){
   Route::resource('ForumThread', 'ForumThreadController');
});*/
/*
Route::group(['middleware' => 'auth'], function(){
    Route::resource('ForumCategory', 'ForumCategoryController');
});
*/

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')

<section class="contact-from-section spad">
    <div class="container">
        <div class="d-flex justify-content-center">
            <div class="col-lg-8">
                <form action="{{ route('categories.store') }}" class="comment-form contact-form" method="POST" enctype="multipart/form-data">
        <div class="panel-heading">Créer une catégorie</div>
                    @csrf
                    @method('POS c.T')
                    <div class="row">
                        <div class="col-lg-12">
                            <label for="title">Titre</label>
                            <input type="text" placeholder="Le titre de la catégorie de forum" name="title">
                        </div>
                        <div class="col-lg-12">
                            <label for="subtitle">Description du forum</label>
                            <input type="text" placeholder="Description rapide de l'objet du forum" name="description">
                        </div>
                        <div class="form-group">
                            <label for="color">Choisir la couleur de fond du forum</label>
                            <select class="form-control" id="color" name="color">
                                @foreach ($colornames as $rgb => $couleur)
                                    <option value="{{ $rgb }}" style="background-color: {{ $rgb }};">{{ $couleur }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="col-lg-12">
                            <label for="isPrivate">Privé</label>
                            <input type="radio" id="isPrivate" name="isPrivate"  value="1" checked="true" />
                            <label for="isPrivate"></label>
                            <input hidden type="radio" id="isPrivate" name="isPrivate"  value="0" checked="false" />
                        </div>


                        <div class="text-center col-lg-12">
                            <button type="submit" class="primary-btn">
                                <i class="fas fa-save"></i>
                                Sauvegarder
                            </button>

                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Modifier une catégorie {{ $category->title }}</div>
                    <div class="panel-body">
                        <form action="{{ route('categories.update', $category->id) }}" class="action" method = "post">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                    <label for="title">Titre du forum</label>
                                    <input type="text" id="title" name= "title" value="{{ $category->title }}" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="description" style="vertical-align: top;">Description du contenu du forum</label>
                                <textarea type="textarea" name="description" rows="4" cols="50">{{ $category->description }} </textarea>
                            </div>
                            <div class="form-group">
                                <label for="color" >Choisir la couleur de fond du forum</label>
                                <select class="form-control" id="color" name="color">
                                    @foreach ($colornames as $rgb => $couleur)
                                        <option value="{{ $rgb }}"  {{ $category->color == $rgb ? 'selected' : '' }} style="background-color:{{ $rgb }};" >{{ $couleur }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="isPrivate">Privé</label>
                                <input type="radio" id="isPrivate" name="isPrivate"  value="1" checked="true" />
                                <label for="isPrivate"></label>
                                <input hidden type="radio" id="isPrivate" name="isPrivate"  value="0" checked="false" />
                            </div>

                            <div class="form-group">
                                <div class="text-center">
                                    <button class="btn btn-success" type= "submit">
                                        Mettre à jour
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div>
        <h2>- Forum -</h2>
        <p class="mt-3">Dès maintenant, créez votre forum en quelques clics !</p>
        <a href="{{ route('categories.create') }}" class="primary-btn mt-3">
            <i class="fas fa-plus"></i>
            Nouveau forum
        </a>
    </div>
<!--  -->
    <div class="row">
        <div class="col-md8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Catégories</div>
                <div class="panel-body">
                    <table class="table table-hover">
                        <thead>
                        <th>
                            Titre
                        </th>
                        <th>
                            Créé le
                        </th>
                        <th>
                            Description
                        </th>

                        <th>
                            Edit
                        </th>
                        <th>
                            Delete
                        </th>
                        </thead>
                        <tbody>
                        @foreach($categories as $category)
                            <tr>
                                <td>{{ $category->title }}</td>
                                <td class="bi-text">
                                    <span><i class="fa fa-clock-o"></i>{{ $category->created_at }}</span>
                                </td>
                                <td class="bi-text">
                                    <a href class="btn font-weight-bold" href="#">{{ $category->description}}</a>
                                </td>
                                <td>
                                    <form action="{{ route('categories.edit', ['category' => $category->id]) }}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <button class="btn btn-xs btn-info" type="submit">Modifier</button>
                                    </form>
                                    <!--   <a href="{ { 'categories.edit', ['category' => $category->id]) }}" class="btn ntn-xs btn-info">EDIT</a> -->
                                </td>

                                <td>
                                    <form action="{{ route('categories.destroy', ['category' => $category->id]) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-xs btn-danger" type="submit"></button>
                                    </form>
                                 <!--   <a href="{ { 'categories.edit', ['category' => $category->id]) }}" class="btn ntn-xs btn-info">EDIT</a> -->
                                </td>
                                <td>
                                  <!--  <a href="{ { 'categories.destroy', ['category' => $category->id]) }}" class="btn ntn-xs btn-danger">SUPPRIMER</a> -->
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

<!-- -->

    <div class="row">
        @foreach($categories  as $category)
            <div class="col-8">
                <div class="card" style="background:{{ $category->color }}; border: 2px solid #0461B6;">
                    <h5 class="card-title">{{ $category->title }}</h5>
                    <div class="card-body">
                        <div class="bi-text">
                            <span><i class="fa fa-clock-o"></i>{{ $category->created_at }}</span>
                        </div>
                        <div class="bi-text">
                            <a class="btn font-weight-bold" href="#">{{ $category->description}}</a>
                            <span><i class="fa fa-clock-o"></i>{{ $category->created_at }}</span>
                        </div>
                    </div>
                </div>
    <!--        <div class="blog-item set-bg" data-setbg="/storage/categories/{ { $category->user_id }}/{ { $category->image }}">
                </div>-->
                <div class="btn-actions d-flex justify-content-center">
                    <form action="{{ route('category.destroy' ['category' => $category]) }}categories destroy" class="">
                        <!--                <a href="{ { route('thread.index', $category->id) }}" class="primary-btn">-->
                        <i class="fas fa-edit"></i>
                        Modifier
                        <!--                </a>--></form>

                </div>

            </div>
        @endforeach
    </div>
</div>
@endsection